version: 0.2
env:
  variables:
    PYTHONPATH: src
phases:
  install:
    commands:
      - pip install pipenv
  build:
    commands:
      - pipenv sync -d
      - pipenv run flake8 src test
      - pipenv run pytest test
  post_build:
    commands:
      - rm  -rf dist
      - pipenv lock -r > requirements.txt
      - pipenv run pip install --target dist -r requirements.txt
      - cp -r src/* dist/
artifacts:
  base-directory: dist
  files: "**/*"
